name: Docker Publish Workflow

on:
  workflow_call:
    inputs:
      platforms:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push multi-platform image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ inputs.image_name }}:latest
            ${{ inputs.image_name }}:${{ github.ref_name }}
          push: true

      #- name: Sign Docker image
      #  uses: sigstore/cosign-installer@v3.7.0
      #  with:
      #    cosign-release: 'v2.4.1'

      #- name: Cosign sign
      #  run: |
      #    cosign sign --key ${{ secrets.COSIGN_KEY }} ${{ inputs.image_name }}:latest
      #    if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/version-* ]]; then
      #      cosign sign --key ${{ secrets.COSIGN_KEY }} ${{ inputs.image_name }}:${{ github.ref_name }}
      #    fi
