name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'version-*'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      dockerfile_path: ./src/Dockerfile
      context_path: ./src
