name: Example Workflow

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

  schedule:
    - cron: '0 0  1 * *'

  workflow_dispatch:

jobs:
  build-and-publish:
    uses: jonas-merkle/docker-workflow/.github/workflows/build-and-publish-docker-image.yml@main
    with:
      registry-image: ghcr.io/cloudflare-tunnel
      work-dir: ./src
