name: Docker Publish Workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          echo "${{ inputs.image }}" | docker load
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/version-* ]]; then
            docker tag ${{ inputs.image }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
            docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
          fi

      #- name: Sign Docker image
      #  uses: sigstore/cosign-installer@v3.7.0
      #  with:
      #    cosign-release: 'v2.4.1'

      #- name: Cosign sign
      #  run: |
      #    cosign sign --key ${{ secrets.COSIGN_KEY }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
      #    if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/version-* ]]; then
      #      cosign sign --key ${{ secrets.COSIGN_KEY }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
      #    fi